"""
Funding Aggregator - AI API Routes
Smart AI search: always returns results — from DB or generated by Groq.
"""
import uuid
from fastapi import APIRouter, Depends, HTTPException
from pydantic import BaseModel
from sqlalchemy.ext.asyncio import AsyncSession
from typing import Optional

from app.database import get_db
from app.models.user import User
from app.api.deps import get_current_user, get_optional_user
from app.schemas.grant import AISearchQuery, GrantListResponse, GrantSearchQuery, GrantResponse
from app.services.ai_service import get_ai_service
from app.services.grant_service import GrantService

router = APIRouter()


class SmartSearchResponse(BaseModel):
    """Response that includes both DB results and AI-generated knowledge."""
    items: list = []
    total: int = 0
    page: int = 1
    per_page: int = 20
    pages: int = 0
    ai_answer: Optional[str] = None
    ai_sources: list = []


@router.post("/search", response_model=SmartSearchResponse)
async def ai_search(
    query: AISearchQuery,
    current_user: User = Depends(get_optional_user),
    db: AsyncSession = Depends(get_db),
):
    """
    Smart AI search — ALWAYS returns useful results.
    
    1. Parses query with Groq AI
    2. Searches the database
    3. If DB has results — returns them
    4. If DB has NO results — asks Groq to generate a comprehensive answer
       with real grant sources and links for Kazakhstan
    """
    ai_service = get_ai_service()
    service = GrantService(db)
    
    # Step 1: Parse natural language query
    parsed = ai_service.parse_natural_language_query(query.query)
    keywords = parsed.get("keywords", [])
    if not keywords:
        keywords = [query.query]
    search_q = " ".join(keywords)
    
    # Step 2: Search database
    params = GrantSearchQuery(
        q=search_q,
        category=parsed.get("category"),
        country=parsed.get("country"),
        amount_min=parsed.get("amount_min"),
        amount_max=parsed.get("amount_max"),
        per_page=query.max_results,
    )
    db_result = await service.get_grants(params)
    
    # Fallback: try raw query if AI-parsed keywords found nothing
    if db_result.total == 0 and search_q != query.query:
        fallback_params = GrantSearchQuery(q=query.query, per_page=query.max_results)
        db_result = await service.get_grants(fallback_params)
    
    # Step 3: ALWAYS generate AI knowledge answer
    ai_answer, ai_sources = _generate_ai_knowledge(ai_service, query.query)
    
    return SmartSearchResponse(
        items=[item.model_dump() for item in db_result.items] if db_result.total > 0 else [],
        total=db_result.total,
        page=db_result.page if db_result.total > 0 else 1,
        per_page=db_result.per_page if db_result.total > 0 else query.max_results,
        pages=db_result.pages if db_result.total > 0 else 0,
        ai_answer=ai_answer,
        ai_sources=ai_sources,
    )


def _generate_ai_knowledge(ai_service, query: str) -> tuple[str, list]:
    """
    Ask Groq AI to generate a comprehensive answer about grants in Kazakhstan.
    Returns (answer_text, list_of_sources).
    """
    import json
    
    system_prompt = """Ты — эксперт по грантам, стипендиям и финансированию в Казахстане.
Пользователь ищет гранты/квоты/субсидии/стипендии. Ты ОБЯЗАН дать полезный развёрнутый ответ на русском языке.

Правила:
1. Опиши ВСЕ реально существующие программы грантов/субсидий/квот по запросу в Казахстане
2. Укажи КОНКРЕТНЫЕ организации, суммы, условия и ссылки
3. Если программа государственная — укажи министерство/ведомство
4. Укажи реальные сайты для подачи заявок
5. Дай практические советы по получению

Верни JSON с ключами:
- "answer": строка с подробным ответом (минимум 300 слов, на русском)
- "sources": массив объектов {"name": "Название источника", "url": "https://...", "description": "Краткое описание"}

Важно: источники должны быть РЕАЛЬНЫМИ казахстанскими сайтами (gov.kz, egov.kz, damu.kz, etc.)"""

    result = ai_service._call_groq(system_prompt, query, json_mode=True)
    
    if result:
        try:
            parsed = json.loads(result)
            answer = parsed.get("answer", "")
            sources = parsed.get("sources", [])
            return answer, sources
        except json.JSONDecodeError:
            # If JSON parsing fails, return raw text
            return result, []
    
    return "AI сервис временно недоступен. Попробуйте позже.", []


@router.post("/analyze/{grant_id}", response_model=dict)
async def analyze_grant(
    grant_id: str,
    current_user: User = Depends(get_current_user),
    db: AsyncSession = Depends(get_db),
):
    """
    Run AI analysis on a specific grant.
    Extracts keywords, generates summary, and suggests categories.
    """
    service = GrantService(db)
    grant = await service.get_grant_by_id(uuid.UUID(grant_id))
    if not grant:
        raise HTTPException(status_code=404, detail="Grant not found")
    
    ai_service = get_ai_service()
    results = {}
    
    if grant.description:
        keywords = ai_service.extract_keywords(grant.description)
        results["keywords"] = keywords
        summary = ai_service.summarize_grant(grant.title, grant.description)
        results["summary"] = summary
    
    categories = await service.get_categories()
    if categories and grant.description:
        cat_names = [c.name for c in categories]
        suggested = ai_service.categorize_grant(grant.title, grant.description, cat_names)
        results["suggested_categories"] = suggested
    
    return results


@router.get("/recommendations", response_model=GrantListResponse)
async def get_recommendations(
    current_user: User = Depends(get_current_user),
    db: AsyncSession = Depends(get_db),
):
    """Get AI-powered grant recommendations based on user's favorites."""
    service = GrantService(db)
    favorites = await service.get_user_favorites(current_user.id, page=1, per_page=10)
    
    if not favorites.items:
        params = GrantSearchQuery(per_page=10, sort_by="created_at", sort_order="desc")
        return await service.get_grants(params)
    
    ai_service = get_ai_service()
    favorite_titles = [g.title for g in favorites.items]
    user_keywords = []
    if current_user.preferences:
        user_keywords = current_user.preferences.get("keywords", [])
    
    search_terms = ai_service.generate_recommendations_prompt(user_keywords, favorite_titles)
    params = GrantSearchQuery(
        q=" ".join(search_terms) if isinstance(search_terms, list) else str(search_terms),
        per_page=10,
    )
    return await service.get_grants(params)
